const affirmations = [
"I grow and improve every day.",
"I let go of all that no longer serves me.",
"I have the power to create change.",
"Every day is full of potential.",
"I am capable of overcoming any challenge I face.",
"I am creative and inspired.",
"I inspire everyone around me.",
"I am worthy of what I desire.",
"I am in charge of my life.",
"I am doing my best, and that is enough.",
"I am proud of myself.",
"I know my worth.",
"I treat myself kindly and with compassion.",
"I give myself permission to be myself.",
"I love myself deeply.",
"I trust myself fully. ",
"I am allowed to take care of myself.",
"​I am worthy of respect and kindness.",
"My needs and wants are important.",
"I am allowed to feel good.",
"I am still learning, so it’s okay to make mistakes.",
];

module.exports = affirmations
